on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install NPM deps
        run: |
            npm install
      - name: Generate hubspot.config.yml and deploy
        env:
          HUBSPOT_PORTAL_ID: ${{ secrets.HUBSPOT_PORTAL_ID }}
          HUBSPOT_API_KEY: ${{ secrets.HUBSPOT_PERSONAL_ACCESS_KEY }}
        run: |
          bin/generate-config.js
          bin/deploy.sh